# Generated by Django 3.2 on 2021-06-12 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('exp', models.CharField(max_length=500)),
                ('resources', models.CharField(max_length=500)),
                ('current', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('plan', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=30)),
                ('degree', models.CharField(choices=[('1', 'Бакалавриат'), ('2', 'Магистратура'), ('3', 'Специалитет')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=75)),
                ('short_desc', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('1', 'Выставка'), ('2', 'Форум'), ('3', 'Сессия'), ('4', 'Круглый стол'), ('5', 'Вебинар'), ('6', 'Демо-день'), ('7', 'Лекция'), ('8', 'On-line лекция'), ('9', 'Стратегическая сессия')], default='1', max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('full_desc', models.CharField(blank=True, max_length=850)),
                ('address', models.CharField(max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('event_site', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Individ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('SNILS', models.CharField(blank=True, max_length=11)),
                ('about', models.CharField(blank=True, max_length=500)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('social', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('comp', models.CharField(blank=True, max_length=500)),
                ('education', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.education')),
            ],
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(max_length=500)),
                ('use', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('competitors', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duty', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('advantage', models.CharField(max_length=500)),
                ('stage', models.CharField(choices=[('1', 'Идея'), ('2', 'Демонстрационный образец'), ('3', 'Продукт'), ('4', 'Масштабирование')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(default='none', max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('poster', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('individ', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.individ')),
                ('team', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.team')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('1', 'Космос'), ('2', 'Авиация'), ('3', 'Сельское хозяйства'), ('4', 'Биотех'), ('5', 'Ядертех'), ('6', 'Строительство'), ('7', 'Мода'), ('8', 'Энергетика'), ('9', 'Финансы'), ('10', 'Питание'), ('11', 'Игры'), ('12', 'Медицина'), ('13', 'Юриспруденция'), ('14', 'Судоходство'), ('15', 'Нанотехнологии'), ('16', 'Нефть и газ'), ('17', 'Торговля'), ('18', 'Безопасность'), ('19', 'IT'), ('20', 'Образование'), ('21', 'Экология'), ('22', 'Образ жизни'), ('23', 'Машиностроение'), ('24', 'Микроэлектроника'), ('25', 'Другое')], default='1', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('about', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.about')),
                ('product', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.product')),
                ('team', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.team')),
            ],
        ),
        migrations.AddField(
            model_name='individ',
            name='position',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.position'),
        ),
        migrations.AddField(
            model_name='individ',
            name='team',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.team'),
        ),
        migrations.AddField(
            model_name='individ',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
