# Generated by Django 3.2 on 2021-06-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_about_education_event_individ_lounge_position_product_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.team'),
        ),
        migrations.AddField(
            model_name='individ',
            name='education',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.education'),
        ),
        migrations.AddField(
            model_name='individ',
            name='position',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.position'),
        ),
        migrations.AddField(
            model_name='individ',
            name='team',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.about'),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.product'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='freelance.team'),
        ),
    ]
